import boto3
from botocore.exceptions import ClientError
from datetime import datetime, timedelta

print('Generate presign url...')

# Replace with your S3 bucket name and object key
BUCKET_NAME = 'bucket-name-here'
OBJECT_KEY = 'file-name-here'

# Create a Boto3 S3 client
s3_client = boto3.client('s3')

# Generate a pre-signed URL for the S3 object that will expire in 1 hour
expiration = datetime.now() + timedelta(hours=1)
try:
    presigned_url = s3_client.generate_presigned_url(
        'get_object',
        Params={
            'Bucket': BUCKET_NAME,
            'Key': OBJECT_KEY
        },
        ExpiresIn=3600, # expires in 1 hour
    )
    print(f'Url will be expired at {expiration}')

    # example url: https://my-s3-bucket.s3.amazonaws.com/my-object?Expires=1620643740&Signature=example_signature&AWSAccessKeyId=example_access_key
    # Expires=1620643740 specifies the Unix timestamp (in seconds) when the pre-signed URL will expire. In this example, the URL will expire on May 10, 2021 at 8:35:40 PM UTC.
    # Signature=example_signature is the signature generated by AWS to authenticate the request. The signature is based on the secret access key associated with the access key ID specified in the URL.
    # AWSAccessKeyId=example_access_key specifies the AWS access key ID used to sign the request.
    print(f'Pre-signed URL: {presigned_url}')
except ClientError as e:
    print(f'Error generating pre-signed URL: {e}')